### ISSUE TITLE
Routes Section 9

### ISSUE THREAD

**Issue by jiuk33** [jiuk33/laravel-test#1]
****

**Comment by calonzolg** [comment]
Test

**Comment by calonzolg** [comment]
@calonzolg

**Comment by jiuk33** [comment]
Hola Carlos, me puedes pasar de nuevo los comando de Ubuntu, los borre por error...

**Comment by calonzolg** [comment]
Tienes estos

composer 

php artisan 

Ahora te recomiendo hacerlos con sail 

./vendor/bin/sail up -d 

./vendor/bin/sail php artisan

./vendor/bin/sail composer

**Comment by jiuk33** [comment]
@calonzolg oye tengo un inconveniente, con un controlador... se quedo en memoria y ahora no puedo hacer nada en php artisan...

**Comment by calonzolg** [comment]
Podes mandarme un screenshot del error ?

**Comment by jiuk33** [comment]
![Uploading php artisan.PNG…]()

**Comment by calonzolg** [comment]
no se subio la foto

**Comment by calonzolg** [comment]
Escribime por Slack si podes

**Comment by jiuk33** [comment]
![php artisan](https://user-images.githubusercontent.com/28868272/122804894-6a94dc00-d296-11eb-893e-adfa4d5cf58e.PNG)
